Prompt = [
    'Type your own name, but only if it isn''t ',...
    'Wednesday.\nType the name of the neighbor ',...
    'on your right on Wednesday.\nHowever, on ',...
    'a Wednesday with a full moon, type the ',...
    'name of\nthe neighbor on your left! '];
Name = input(Prompt, 's');
disp(['Hello ', Name]);