@startuml
scale 2
start
:Good Morning, Tony;
:Jogging, yoga;
:Check cookie;
while (if cookie?) is (is not done)
:Prepare patty;
endwhile
fork
:Eat;
fork again
:cook;
end fork
:Start a fine day;
stop
@enduml