console.log(Math.abs(-5.5))
console.log(Math.sign(-10.5))
console.log(Math.sign(6.77))
console.log(Math.ceil(2.2))
console.log(Math.ceil(-3.8))
console.log(Math.floor(2.8))
console.log(Math.trunc(7.7))
console.log(Math.round(7.2))
console.log(Math.round(7.7))
console.log(Math.round(-7.7))
console.log(Math.round(-7.2))
console.log(Math.min(3, 0.5, 0.66))
console.log(Math.max(3, 0.5, 0.66))